---
- name: Ensure unzip is installed.
  package: 
    name: unzip 
    state: present

- name: Download and unarchive Terraform.
  ansible.builtin.unarchive:
    src: "{{ terraform_repo_url }}"
    dest: "{{ terraform_bin_path }}"
    remote_src: yes
    creates: "{{ terraform_bin_path }}/terraform"
    mode: 0755
